language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.0
  - android-25
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
jdk:
- oraclejdk8
notifications:
  slack:
    secure: bSAqWXHf2h+miuS2rE/lTfCsEB5LHI7neNlr18K9B/c+ShEKIBzZj0PfE74kVO0GVUY8TVfHpBoEW8mxw3zvALHDrM/sTGcn7jX5jbnRLA30TNj8YQJjdN/aXguC/YOP13dc2MIo08kzmmKKhTqfMQgb2Lwbym9X9BGRpFYEw8ns98H/9o3GLEybqk9P6kPdbMxQvYA5C/YmwtfUdkQMTJclSKkSQzQR9kehqgvQgHZbpmlNps9IDgpZvyS9XKkTTGfVAfGKGTt4RFLB7zwLMog5p3p2YHAOD66A/yxjb2VZ4n1hDCG5AV8duF9U7lT7ZIYFjWuingAlJoJv4aWYm9xvxPGjtFUQJNvXjWNEeZd6tvQ/cc5/FSPyuLdJloPGMzoimlD1CaJswDo/hBRHKOzNDMTzCbKw91yidb5K+vWldXnefaXPhtNxeJl2EPOzNpuhAA0K0urXjOx/0VrVD18On60XQzY2YBGUpKDvu+xZStfeWOaYpxfGE+SKVCN7c0Uy0PETfBewPi5c+8Xfp+6oSWwMmckj2naLyO/7yjXTCrg2tU+aiNmebJSYiJL/pnJLIen8A1561ES7qnXP5l91O2tgrPQf21inYG2j48DaSzjG8DMFRr6v0qMV9H6IVhNFePTHdgg1YoqVm3xgeKjO5RzsqY1dTTSJ8xN7Bjo=
